In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [4]:
my_list_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_list_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
my_matrix = np.array(my_list_matrix)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# there is an another method called arange
# the arange method takes 2 arguments (values are separated by comma)
np.arange(0,10) # start index (inlcuded) and end index (not included)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros((4, 4)) # the zeros method takes single argument (cannot pass more than one value)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# we cannot pass more than one value, since the method takes single argument
# however we need to pass more than one values (row, column)
# we put the 2 alues inside a tuple (is another data structre that use () as enclosing characters
# tuple is actually a readonly list
# eventually it becomes a sigle argument to the zeros method
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4, 4)) * 2.3 #matrix multiplication with scalar value

array([[2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3]])

In [13]:
np.eye(4) # 4x4 matrix (identity matrix are always square matrix)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(0, 8, 2)

array([0, 2, 4, 6])

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [18]:
np.random.rand(5)

array([0.55335212, 0.84444985, 0.14338952, 0.40798176, 0.36903737])

In [19]:
np.random.rand(3, 3) #uniform distribution

array([[0.24817474, 0.16106683, 0.97549648],
       [0.45440154, 0.27027978, 0.64933518],
       [0.59502176, 0.73044987, 0.8661309 ]])

In [20]:
np.random.randn(10) #normal distribution

array([-0.46722515,  1.10892798, -1.6582518 , -2.14027093, -1.1882935 ,
       -1.19930147, -0.36011494,  1.72940632, -0.59527916,  1.51333482])

In [21]:
np.random.randint(1,100, 10)

array([ 5, 99, 65, 89, 19, 33, 72, 85, 48, 54])

In [22]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [10]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
np.random.seed(41)
ranarr = np.random.randint(0,50,10)
ranarr

array([ 0, 35, 12, 34, 16,  1, 25, 23, 21, 26])

In [5]:
arr.shape

(25,)

In [20]:
reshaped = arr.reshape(5,5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
reshaped.shape

(5, 5)

In [12]:
ranarr.max()

35

In [17]:
ranarr.argmin()

0

In [2]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
slice_arr = arr[0:6]
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100, 100])

In [5]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [6]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
slice_arr = arr[0:6].copy
slice_arr

<function ndarray.copy>

In [8]:
slice_arr = arr[0:6].copy()
slice_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100, 100])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
my_matrix = arr[:]
my_matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arrone = np.arange(0,10)
arrtwo = np.arange(100,110)
arrone
arrtwo

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [13]:
arrone + arrtwo

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [14]:
arrtwo - arrone
arrtwo

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [15]:
# UNIVERSAL FUNCTIONS
arr.max()

24

In [16]:
np.max(arr) 

24