In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf

In [3]:
celsius = np.arange(0, 101, 10  )
celsius

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
fahrenheit = (celsius *9/5) + 32
fahrenheit

array([ 32.,  50.,  68.,  86., 104., 122., 140., 158., 176., 194., 212.])

In [5]:
X_train = celsius
y_train = fahrenheit

In [6]:
#instance
model = tf.keras.Sequential()

In [7]:
model.add(tf.keras.layers.Dense(units=1, input_shape=[1]))  #units = 1, input_shape = 1

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.1), loss='mean_squared_error')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
epochs_hist = model.fit(X_train, y_train, epochs=500)

Epoch 1/500


1/1 [==============================] - 0s 10ms/step - loss: 0.6258
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6214
Epoch 3/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6170
Epoch 4/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6127
Epoch 5/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6083
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6040
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 0.5997
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 0.5955
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.5913
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 0.5871
Epoch 11/500
1/1 [==============================] - 0s 10ms/step - loss: 0.5829
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 0.5788
Epoch 13/500
1/1 [==============================] - 0s 8ms/step - loss:

In [13]:
epochs_hist.history

1/1 [==============================] - 0s 264ms/step


array([[139.08372],
       [171.2943 ],
       [233.82068]], dtype=float32)

In [16]:

model.predict([60, 77, 110])

{'loss': [0.6258361339569092,
  0.621415913105011,
  0.6170263290405273,
  0.612663984298706,
  0.608328104019165,
  0.6040174961090088,
  0.5997399687767029,
  0.595490038394928,
  0.591270387172699,
  0.5870673060417175,
  0.5828996300697327,
  0.5787544250488281,
  0.574641227722168,
  0.5705477595329285,
  0.5664850473403931,
  0.5624499917030334,
  0.5584366321563721,
  0.5544506907463074,
  0.5504898428916931,
  0.5465603470802307,
  0.5426524877548218,
  0.5387679934501648,
  0.5349094867706299,
  0.5310812592506409,
  0.5272725224494934,
  0.523488461971283,
  0.5197318196296692,
  0.5159939527511597,
  0.512288510799408,
  0.508604109287262,
  0.5049421787261963,
  0.5013049840927124,
  0.4976947009563446,
  0.49410247802734375,
  0.4905399978160858,
  0.48699501156806946,
  0.4834758937358856,
  0.47998112440109253,
  0.47650831937789917,
  0.4730570614337921,
  0.4696305990219116,
  0.46622514724731445,
  0.4628410339355469,
  0.45948174595832825,
  0.45614564418792725,
  0.